### ISSUE TITLE
Don't autoplay

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/nanoanimation#4]
By default, web animations play right after declared, this means that the readme example is wrong.
Now, if you want to wait on user interaction to play  an animation, `pause` must be called right after the `animate` method is called.

Right now this can't be done, so I think there are two options.

1. Add an `autoplay` option somewhere
2. Change current behaviour to always call `pause` after animation is created, so users must explicitly call `play` to run animations.

I'm inclined to option 2. What do you think?

**Comment by yoshuawuyts** [comment]
@YerkoPalma 2 sounds reasonable!
